theme: jekyll-theme-minimal
title: わかばやしのホームページ


！[ロゴ](https://www.canva.com/design/DAE-kmaTyso/_LlFdEYhHXeKEJsV_WLo9Q/view?utm_content=DAE-kmaTyso&utm_campaign=celebratory_first_publish&utm_medium=link&utm_source=celebratory_first_publish）


description: GitHub Pagesで作りました
logo: /logo.png