theme: jekyll-theme-minimal
title: わかばやしのホームページ
description: GitHub Pagesで作りました
logo: /https://www.canva.com/design/DAE-kmaTyso/SwyQ9OzR4kTCOf36FgcASg/edit?utm_content=DAE-kmaTyso&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton